export const menuData = [
  // 🥩 BBQ / Grill - BEEF
  {
    id: 1,
    name: "홍대 제비추리 Hongdae Jebichuri",
    description: "2GR Full blood Wagyu (GF, DF)",
    price: "Normal $39 / Supersize $54",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_6.webp",
    isNew: true, isHot: false, isIce: false,
  },
  {
    id: 2,
    name: "부채살 Buchaesal",
    description: "Oyster blade, Wagyu MBS7 (GF, DF)",
    price: "$38",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_8.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 3,
    name: "치마살 Chimasal",
    description: "Bavette, Wagyu MBS9+ (GF, DF)",
    price: "$39",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_7.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 4,
    name: "토시살 Toshisal",
    description: "Hanger steak, 2GR Full blood Wagyu (GF, DF)",
    price: "$38",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_6.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 5,
    name: "갈비살 Galbisal",
    description: "Rib fingers, Wagyu MBS5 (GF, DF)",
    price: "$29",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 6,
    name: "특양구이 Teukyang gui",
    description: "Mountain chain tripe marinated with chilli, garlic and black pepper (150g)",
    price: "$35",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 7,
    name: "꽃살 Kkotsal",
    description: "Shortrib meat, Wagyu MBS7 (GF, DF)",
    price: "$49",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_7.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 8,
    name: "우삼겹 Woosamgyeop",
    description: "Soy glazed thin Wagyu brisket (DF)",
    price: "$26",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 9,
    name: "LA 갈비 LA Galbi",
    description: "LA Cut short ribs marinated in Galbi sauce, Grass fed Black Angus (200g)",
    price: "$31",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_5.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 10,
    name: "양념 업진살 Yangyeum Upjinsal",
    description: "Karubi Plate marinated with Soy and green onion, Wagyu MBS9+ (DF)",
    price: "$38",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_5.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 11,
    name: "홍대 마늘 주물럭 Hongdae garlic bomb jumuluk",
    description: "Rib fingers garlic jumuluk style, Wagyu MBS5 (GF, DF)",
    price: "$31",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_5.webp",
    isNew: false, isHot: false, isIce: false,
  },

  // 🐷 BBQ / Grill - PORK
  {
    id: 12,
    name: "제주도식 목살 Moksal",
    description: "Pork scotch fillet, Jeju-island style cut. Includes Jeju fish sauce dip",
    price: "$22",
    category: "BBQ / Grill",
    subcategory: "PORK",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_69.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 13,
    name: "삼겹살 Samgyeopsal",
    description: "Free ranged Pork belly (GF, DF)",
    price: "$22",
    category: "BBQ / Grill",
    subcategory: "PORK",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_70.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 14,
    name: "미식가용 삼겹살 Misikgayong samgyeopsal",
    description: "Free ranged Extra fatty Pork belly (Limited quantity)",
    price: "$24",
    category: "BBQ / Grill",
    subcategory: "PORK",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_70.webp",
    isNew: true, isHot: false, isIce: false,
  },
  {
    id: 15,
    name: "항정살 Hangjeongsal",
    description: "Pork jowl (GF, DF)",
    price: "$25",
    category: "BBQ / Grill",
    subcategory: "PORK",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_70.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 16,
    name: "돼지갈비 Dwaeji Galbi",
    description: "Free ranged Pork rib meat marinated with soy & apple (DF)",
    price: "$24",
    category: "BBQ / Grill",
    subcategory: "PORK",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false, isHot: false, isIce: false,
  },

  // 🥗 K-BBQ & FRIENDS
  {
    id: 17,
    name: "쌈 Ssam",
    description: "Seasonal Crudités and leafy vegetables (GF, DF, VG)",
    price: "$5",
    category: "BBQ / Grill",
    subcategory: "K-BBQ & FRIENDS",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_49.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 18,
    name: "고깃집 된장찌개 Gogijib Doenjang jjigae",
    description: "Deonjang, Wagyu, Seafood broth, tofu, chilli, bowl of rice",
    price: "$19",
    category: "BBQ / Grill",
    subcategory: "K-BBQ & FRIENDS",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_12.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 19,
    name: "폭탄계란찜 Poktan gyeranjjim",
    description: "6 Eggs, spring onion, sesame (GF, DF)",
    price: "$19",
    category: "BBQ / Grill",
    subcategory: "K-BBQ & FRIENDS",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_87.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 20,
    name: "육회 비빔밥 Yukhoe Bibimbap",
    description: "Bibimbap with raw 9+ wagyu and vegetables",
    price: "$29",
    category: "BBQ / Grill",
    subcategory: "K-BBQ & FRIENDS",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_21.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 21,
    name: "양푼 비빔밥 Yangpoon Bibimbap",
    description: "Bibimbap with fried egg and vegetables (DF, V)",
    price: "$23",
    category: "BBQ / Grill",
    subcategory: "K-BBQ & FRIENDS",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_18.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 22,
    name: "물쫄면 Muljjolmyeon",
    description: "Spicy and tangy cold noodles (DF, VG)",
    price: "$19",
    category: "BBQ / Grill",
    subcategory: "K-BBQ & FRIENDS",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_90.webp",
    isNew: false, isHot: false, isIce: true,
  },
  {
    id: 23,
    name: "모듬버섯구이 Beoseot gui",
    description: "Assorted mushrooms, garlic oil, soy dressing",
    price: "$15",
    category: "BBQ / Grill",
    subcategory: "K-BBQ & FRIENDS",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_50.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 24,
    name: "명이나물과 마늘쫑 장아찌 Myungyi & Maneul jjong jangacchi",
    description: "Soy pickled wild garlic leaf and garlic shoots",
    price: "$8",
    category: "BBQ / Grill",
    subcategory: "K-BBQ & FRIENDS",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_51.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 25,
    name: "쑥갓무침 Ssukgat muchim",
    description: "Crown daisy salad with plum dressing",
    price: "$12",
    category: "BBQ / Grill",
    subcategory: "K-BBQ & FRIENDS",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_67.webp",
    isNew: false, isHot: false, isIce: false,
  },

  // ✨ Hongdae Pocha Specials
  {
    id: 26,
    name: "진주식 육회와 해시브라운 Gochujang Yukhoe & hashbrown",
    description: "Jinju style beef tartare on golden hashbrown 2PCS (DF)",
    price: "$20",
    category: "Hongdae Pocha Specials",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_33.webp",
    isNew: true, isHot: false, isIce: false,
  },
  {
    id: 27,
    name: "육회 Yukhoe",
    description: "Korean style raw beef with rocket salad (DF, GF)",
    price: "$33",
    category: "Hongdae Pocha Specials",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_29.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 28,
    name: "항정살 수육 Hangjeong Suyuk",
    description: "Steamed pork jowl and braised kimchi (DF)",
    price: "$35",
    category: "Hongdae Pocha Specials",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_58.webp",
    isNew: true, isHot: false, isIce: false,
  },
  {
    id: 29,
    name: "돌판 우삼겹 짜파게티 Dolpan chapagetti",
    description: "Sizzling Chapagetti with beef brisket",
    price: "$43",
    category: "Hongdae Pocha Specials",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_60.webp",
    isNew: true, isHot: false, isIce: false,
    spiceLevel: 1, // 🌶️
  },

  // 🥞 Pancakes & Stir-fried
  {
    id: 30,
    name: "새우미나리전 Saewoo Minari jeon",
    description: "Crispy Korean water parsley pancake with QLD prawns",
    price: "$26",
    category: "Hongdae Pocha Specials",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_35.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 31,
    name: "제육볶음 Jeyuk bokkeum",
    description: "Spicy Stir fried pork belly on sizzling plate",
    price: "$23",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 32,
    name: "소떡소떡 Sotteok Sotteok",
    description: "Fried rice cake and cheese kransky (DF)",
    price: "$20",
    category: "Side Menu",
    subcategory: "Small Plates",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_37.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 33,
    name: "오삼불고기와 콩나물쌈 Osambulgogi",
    description: "Spicy Stir fried Local cuttlefish and pork",
    price: "$48",
    category: "Hongdae Pocha Specials",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false, isHot: false, isIce: false,
    spiceLevel: 2, // 🌶️🌶️
  },
  {
    id: 34,
    name: "김치 두루치기 Kimchi duruchigi",
    description: "Stir fried Kimchi and pork with gochujang sauce",
    price: "$46",
    category: "Hongdae Pocha Specials",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false, isHot: false, isIce: false,
    spiceLevel: 1, // 🌶️
  },
  {
    id: 35,
    name: "치즈불닭 Cheese buldak",
    description: "Sizzling chilli cheese chicken (SPICY)",
    price: "$46",
    category: "Hongdae Pocha Specials",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_92.webp",
    isNew: false, isHot: false, isIce: false,
    spiceLevel: 3, // (🌶️~🌶️🌶️🌶️) 최대치 표시
  },

  // 🍗 Fried Chicken
  {
    id: 36,
    name: "순살후라이드치킨 KFC",
    description: "Boneless Korean fried chicken, original flavor",
    price: "$22",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_4.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 37,
    name: "순살양념치킨 Yangnyum KFC",
    description: "Boneless Korean fried chicken with sweet and spicy sauce",
    price: "$25",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_4.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 38,
    name: "순살간장치킨 Ganjang KFC",
    description: "Boneless Korean Fried chicken with garlic soy",
    price: "$25",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_4.webp",
    isNew: false, isHot: false, isIce: false,
  },

  // 🍡 Pocha Staples & Snacks
  {
    id: 39,
    name: "튀김어묵 Crispy Eomuk",
    description: "Crispy Fishcakes with wasabi mayo",
    price: "$14",
    category: "Side Menu",
    subcategory: "Small Plates",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 40,
    name: "콘치즈 koncheeze",
    description: "Sweet corn fritter 2PCS (DF, VG)",
    price: "$16",
    category: "Side Menu",
    subcategory: "Small Plates",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_73.webp",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 41,
    name: "김말이 Gim-mari",
    description: "Fried seaweed rolls 8PCS (DF)",
    price: "$14",
    category: "Side Menu",
    subcategory: "Small Plates",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 42,
    name: "떡볶이 Tteokbokki",
    description: "Gochujang sauce rice cakes (DF)",
    price: "$14",
    category: "Side Menu",
    subcategory: "Small Plates",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_74.webp",
    isNew: false, isHot: false, isIce: false,
    spiceLevel: 1, // 🌶️
  },
  {
    id: 43,
    name: "컵라면볶음밥 Cup-ramyun fried rice",
    description: "Shin cup noodles, kimchi, melted burger cheese",
    price: "$18",
    category: "Side Menu",
    subcategory: "Small Plates",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_66.webp",
    isNew: false, isHot: false, isIce: false,
    spiceLevel: 1, // 🌶️
  },
  {
    id: 44,
    name: "고구마치즈스틱 Goguma Cheese stick",
    description: "4 Cheese and sweet potato spring roll 2PCS",
    price: "$16",
    category: "Side Menu",
    subcategory: "Small Plates",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 45,
    name: "골뱅이무침 Golbang-e muchim",
    description: "Spicy and tangy whelk shell salad (DF)",
    price: "$39",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_75.webp",
    isNew: false, isHot: false, isIce: false,
    spiceLevel: 1, // 🌶️
  },

  // 🍲 Soups and Hotpot
  {
    id: 46,
    name: "포차 우동 Pocha udong",
    description: "Korean pocha style udong, seafood broth",
    price: "$25",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 47,
    name: "생고기 김치찌개 Saeng gogi kimchi jjigae",
    description: "Kimchi stew with fresh pork, tofu, rice",
    price: "$28",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_13.webp",
    isNew: false, isHot: false, isIce: false,
    spiceLevel: 1, // 🌶️
  },
  {
    id: 48,
    name: "갈비곱창전골 Galbi gopchang jeongol",
    description: "Shortrib and Beef intestine hot pot",
    price: "$63",
    category: "Hongdae Pocha Specials",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_46.webp",
    isNew: false, isHot: false, isIce: false,
    spiceLevel: 1, // 🌶️
  },
  {
    id: 49,
    name: "명란곤이전골 Myungran goni jeongol",
    description: "Spicy roe and cod milt hot pot (DF)",
    price: "$69",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 50,
    name: "홍합어묵탕 Honghap Eomuktang",
    description: "Fish cake soup with SA mussel",
    price: "$32",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 51,
    name: "쫄면순두부 Jjolmyun Sundubu",
    description: "Spicy silken tofu soup with NZ squid",
    price: "$28",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_59.webp",
    isNew: false, isHot: false, isIce: false,
    spiceLevel: 1, // 🌶️
  },
  {
    id: 52,
    name: "부대전골 Budae Jeongol",
    description: "Korean army soup with ham, sausage, Ramyun",
    price: "$49",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_44.webp",
    isNew: false, isHot: false, isIce: false,
  },

  // 🍦 Dessert
  {
    id: 53,
    name: "바나나우유/녹차 아이스크림 Banana oo-yoo/ Nokcha Ice cream",
    description: "Grandma’s snack mix, sesame, perilla oil",
    price: "$12",
    category: "Dessert",
    image: "/assets/HongdaePocha/HongdaePocha_Menu_Image/BandiView_96.webp",
    isNew: false, isHot: false, isIce: true,
  },

  // ➕ Accompaniments / Extras
  {
    id: 54,
    name: "공기밥 Steamed rice",
    price: "$4",
    category: "Extras",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 55,
    name: "갈치속젓 Jeju fish sauce dip",
    price: "$6",
    category: "Extras",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 56,
    name: "치즈 추가 Cheese",
    description: "Mozzarella $4 / Burger cheese $2",
    price: "$2-$4",
    category: "Extras",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 57,
    name: "소스 추가 Extra sauce",
    price: "$3",
    category: "Extras",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false, isHot: false, isIce: false,
  },
  {
    id: 58,
    name: "우동/라면/쫄면 사리 Noodle Add-ons",
    price: "$4",
    category: "Extras",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false, isHot: false, isIce: false,
  },
  // 🍺 DRINKS (기존 목록 유지하며 ID 재부여)
  { id: 59, name: "처음처럼(Chumchurum)", category: "DRINKS", subcategory: "SOJU", image: "/assets/HongdaePocha/HongdaePocha_image/Chumchurum.jpg", isNew: false, isHot: false, isIce: false },
  { id: 60, name: "새로(Saero)", category: "DRINKS", subcategory: "SOJU", image: "/assets/HongdaePocha/HongdaePocha_image/sero.jpg", isNew: false, isHot: false, isIce: false },
  { id: 61, name: "선양(Sunyang)", category: "DRINKS", subcategory: "SOJU", image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg", isNew: false, isHot: false, isIce: false },
  { id: 62, name: "복숭아(peach)", category: "DRINKS", subcategory: "SOJU", image: "/assets/HongdaePocha/HongdaePocha_image/soonpeach.jpg", isNew: false, isHot: false, isIce: false },
  { id: 63, name: "청포도(green grape)", category: "DRINKS", subcategory: "SOJU", image: "/assets/HongdaePocha/HongdaePocha_image/soongrape.jpg", isNew: false, isHot: false, isIce: false },
  { id: 64, name: "요거트(yogurt)", category: "DRINKS", subcategory: "SOJU", image: "/assets/HongdaePocha/HongdaePocha_image/soonyogurt.jpg", isNew: false, isHot: false, isIce: false },
  { id: 65, name: "카스(Cass)", category: "DRINKS", subcategory: "BEER", image: "/assets/HongdaePocha/HongdaePocha_image/Cass.jpg", isNew: false, isHot: false, isIce: false },
  { id: 66, name: "테라(Terra)", category: "DRINKS", subcategory: "BEER", image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg", isNew: false, isHot: false, isIce: false },
  { id: 67, name: "크러쉬(Krush)", category: "DRINKS", subcategory: "BEER", image: "/assets/HongdaePocha/HongdaePocha_image/krush.jpg", isNew: false, isHot: false, isIce: false },
  { id: 68, name: "지평(Jipyeong makgeolli)", category: "DRINKS", subcategory: "MAKGEOLLI", image: "/assets/HongdaePocha/HongdaePocha_image/jipungMakgeolli.jpg", isNew: false, isHot: false, isIce: false },
  { id: 69, name: "장수(Jangsoo draft makgeolli)", category: "DRINKS", subcategory: "MAKGEOLLI", image: "/assets/HongdaePocha/HongdaePocha_image/Makgeolli.jpg", isNew: false, isHot: false, isIce: false },
  { id: 70, name: "알밤(Chestnut makgeolli)", category: "DRINKS", subcategory: "MAKGEOLLI", image: "/assets/HongdaePocha/HongdaePocha_image/Chestnut.jpg", isNew: false, isHot: false, isIce: false },
  { id: 71, name: "별빛청하(Chungha sparkling wine)", category: "DRINKS", subcategory: "KOREAN WINE", image: "/assets/HongdaePocha/HongdaePocha_image/sparkingwine.jpg", isNew: false, isHot: false, isIce: false },
  { id: 72, name: "복분자(Bokbunja)", category: "DRINKS", subcategory: "KOREAN WINE", image: "/assets/HongdaePocha/HongdaePocha_image/bokbunja.jpg", isNew: false, isHot: false, isIce: false },
  { id: 73, name: "Princess peach", category: "DRINKS", subcategory: "Cocktails", image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg", isNew: false, isHot: false, isIce: false },
  { id: 74, name: "Go banana's", category: "DRINKS", subcategory: "Cocktails", image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg", isNew: false, isHot: false, isIce: false },
  { id: 75, name: "Yuja drop", category: "DRINKS", subcategory: "Cocktails", image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg", isNew: false, isHot: false, isIce: false },
  { id: 76, name: "밀키스(Milkis)", category: "DRINKS", subcategory: "SOFT DRINKS", image: "/assets/HongdaePocha/HongdaePocha_image/creamsoda.jpg", isNew: false, isHot: false, isIce: false },
  { id: 77, name: "봉봉(Bongbong grape juice)", category: "DRINKS", subcategory: "SOFT DRINKS", image: "/assets/HongdaePocha/HongdaePocha_image/bongbong.jpg", isNew: false, isHot: false, isIce: false },
  { id: 78, name: "갈아만든배(pear juice)", category: "DRINKS", subcategory: "SOFT DRINKS", image: "/assets/HongdaePocha/HongdaePocha_image/LDH.jpg", isNew: false, isHot: false, isIce: false },
];