export const menuData = [
  {
    id: 1,
    name: "처음처럼(Chumchurum)",
    category: "DRINKS",
    subcategory: "SOJU",
    image: "/assets/HongdaePocha/HongdaePocha_image/Chumchurum.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 2,
    name: "새로(Saero)",
    category: "DRINKS",
    subcategory: "SOJU",
    image: "/assets/HongdaePocha/HongdaePocha_image/sero.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 3,
    name: "선양(Sunyang)",
    category: "DRINKS",
    subcategory: "SOJU",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 4,
    name: "복숭아(peach)",
    category: "DRINKS",
    subcategory: "SOJU",
    image: "/assets/HongdaePocha/HongdaePocha_image/soonpeach.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 5,
    name: "청포도(green grape)",
    category: "DRINKS",
    subcategory: "SOJU",
    image: "/assets/HongdaePocha/HongdaePocha_image/soongrape.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 6,
    name: "요거트(yogurt)",
    category: "DRINKS",
    subcategory: "SOJU",
    image: "/assets/HongdaePocha/HongdaePocha_image/soonyogurt.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 7,
    name: "카스(Cass)",
    category: "DRINKS",
    subcategory: "BEER",
    image: "/assets/HongdaePocha/HongdaePocha_image/Cass.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 8,
    name: "테라(Terra)",
    category: "DRINKS",
    subcategory: "BEER",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 9,
    name: "크러쉬(Krush)",
    category: "DRINKS",
    subcategory: "BEER",
    image: "/assets/HongdaePocha/HongdaePocha_image/krush.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 10,
    name: "지평(Jipyeong makgeolli)",
    category: "DRINKS",
    subcategory: "MAKGEOLLI",
    image: "/assets/HongdaePocha/HongdaePocha_image/jipungMakgeolli.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 11,
    name: "장수(Jangsoo draft makgeolli)",
    category: "DRINKS",
    subcategory: "MAKGEOLLI",
    image: "/assets/HongdaePocha/HongdaePocha_image/Makgeolli.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 12,
    name: "알밤(Chestnut makgeolli)",
    category: "DRINKS",
    subcategory: "MAKGEOLLI",
    image: "/assets/HongdaePocha/HongdaePocha_image/Chestnut.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 13,
    name: "Marty's Block Sauvignon Blanc, Riverland SA",
    category: "DRINKS",
    subcategory: "WINE",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 14,
    name: "Redbank Pinot Grigio, King Valley VIC",
    category: "DRINKS",
    subcategory: "WINE",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 15,
    name: "Marty's Block Cabernet Shiraz, Riverland SA",
    category: "DRINKS",
    subcategory: "WINE",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 16,
    name: "Opawa Marlborough Pinot Noir, Marlborough NZ",
    category: "DRINKS",
    subcategory: "WINE",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 17,
    name: "별빛청하(Chungha sparkling wine)",
    category: "DRINKS",
    subcategory: "KOREAN WINE",
    image: "/assets/HongdaePocha/HongdaePocha_image/sparkingwine.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 18,
    name: "복분자(Bokbunja)",
    category: "DRINKS",
    subcategory: "KOREAN WINE",
    image: "/assets/HongdaePocha/HongdaePocha_image/bokbunja.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 19,
    name: "Princess peach peach soju, whiskey, lemon",
    category: "DRINKS",
    subcategory: "Cocktails",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 20,
    name: "Go banana's strawberry soju, vodka, banana, watermelon",
    category: "DRINKS",
    subcategory: "Cocktails",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 21,
    name: "Yuja drop yuzu soju, vodka, lychee",
    category: "DRINKS",
    subcategory: "Cocktails",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 22,
    name: "Coke",
    category: "DRINKS",
    subcategory: "SOFT DRINKS",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 23,
    name: "Coke no sugar",
    category: "DRINKS",
    subcategory: "SOFT DRINKS",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 24,
    name: "Sprite",
    category: "DRINKS",
    subcategory: "SOFT DRINKS",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 25,
    name: "밀키스(Milkis)",
    category: "DRINKS",
    subcategory: "SOFT DRINKS",
    image: "/assets/HongdaePocha/HongdaePocha_image/creamsoda.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 26,
    name: "봉봉(Bongbong grape juice)",
    category: "DRINKS",
    subcategory: "SOFT DRINKS",
    image: "/assets/HongdaePocha/HongdaePocha_image/bongbong.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 27,
    name: "갈아만든배(pear juice)",
    category: "DRINKS",
    subcategory: "SOFT DRINKS",
    image: "/assets/HongdaePocha/HongdaePocha_image/LDH.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 28,
    name: "우삼겹 Woosamgyeop",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 29,
    name: "갈비살 Galbisal",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_image/galbisal.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 30,
    name: "홍대 마늘주물럭 Hongdae garlic bomb jiumulluk",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_image/hongdaegalic.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 31,
    name: "부채살 Buchaesal",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 32,
    name: "꽃살 Kkotsal",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_image/kkotsal.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 33,
    name: "치마살 Chimasal",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_image/Chimasal.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 34,
    name: "LA 갈비 LA Galbi",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_image/la.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 35,
    name: "양구이 Yang-gui",
    category: "BBQ / Grill",
    subcategory: "BEEF",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 36,
    name: "삼겹살 Samgyeopsal",
    category: "BBQ / Grill",
    subcategory: "PORK",
    image: "/assets/HongdaePocha/HongdaePocha_image/samgyeopsal.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 37,
    name: "항정살 Hangjeongsal",
    category: "BBQ / Grill",
    subcategory: "PORK",
    image: "/assets/HongdaePocha/HongdaePocha_image/hangjeongsal.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 38,
    name: "돼지갈비 Dwaeji galbi",
    category: "BBQ / Grill",
    subcategory: "PORK",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 39,
    name: "쌈 (Ssam)",
    category: "BBQ / Grill",
    subcategory: "K-BBQ & FRIENDS",
    image: "/assets/HongdaePocha/HongdaePocha_image/Ssam.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 40,
    name: "폭탄 계란찜 (Poktan gyeranjjim)",
    category: "BBQ / Grill",
    subcategory: "K-BBQ & FRIENDS",
    image: "/assets/HongdaePocha/HongdaePocha_image/poktanegg.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 41,
    name: "물쫄면 (Muljjolmyeon)",
    category: "BBQ / Grill",
    subcategory: "K-BBQ & FRIENDS",
    image: "/assets/HongdaePocha/HongdaePocha_image/jjolmyeon.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 42,
    name: "고기집 된장찌개 (GOGIJIB DOENJANG JJIGAE)",
    category: "BBQ / Grill",
    subcategory: "K-BBQ & FRIENDS",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 43,
    name: "새우미나리전 (Saewoo minari jeon)",
    category: "Hongdae Pocha Specials",
    image: "/assets/HongdaePocha/HongdaePocha_image/saewoominarijeon.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 44,
    name: "반반 옛날통닭 (Yetnal tongdak)",
    category: "Hongdae Pocha Specials",
    image: "/assets/HongdaePocha/HongdaePocha_image/banbantongdak.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 45,
    name: "매운돼지갈비찜 (Maewoon dwaejigalbijjim)",
    category: "Hongdae Pocha Specials",
    image: "/assets/HongdaePocha/HongdaePocha_image/galbijjim.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 46,
    name: "오삼불고기 (Osambulgoi)",
    category: "Hongdae Pocha Specials",
    image: "/assets/HongdaePocha/HongdaePocha_image/osambulgoggi.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 47,
    name: "갈비곱창전골 (Galbi gopchang jeongol)",
    category: "Hongdae Pocha Specials",
    image: "/assets/HongdaePocha/HongdaePocha_image/galbigopchang.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 48,
    name: "순살 후라이드치킨 KFC(boneless)",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_image/normalkfc.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 49,
    name: "순살 양념치킨 Yangnyum KFC(boneless)",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_image/yangnyumkfc.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 50,
    name: "순살 간장치킨 Ganjang KFC(boneless)",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_image/ganjangkfc.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 51,
    name: "제육볶음 Jeyuk bokkeum",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_image/jeyuk.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 52,
    name: "국물 닭발 Gukmul dakbal",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_image/gukmuldakbal.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 53,
    name: "홍합 어묵탕 Honghap omuktang",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_image/honghap.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 54,
    name: "쫄면 순두부 Jjolmyun sundubu",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_image/jjolmyunsundubu.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 55,
    name: "부대전골 Budae jeongol",
    category: "Pocha Staples to Share",
    image: "/assets/HongdaePocha/HongdaePocha_image/budaejeongol.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 56,
    name: "튀김 어묵 Crispy-omuk",
    category: "Side Menu",
    subcategory: "Small Plates",
    image: "/assets/HongdaePocha/HongdaePocha_image/crispyeomuk.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 57,
    name: "김말이 Gim-mari",
    category: "Side Menu",
    subcategory: "Small Plates",
    image: "/assets/HongdaePocha/HongdaePocha_image/kimmali.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 58,
    name: "떡볶이 Tteokbokki",
    category: "Side Menu",
    subcategory: "Small Plates",
    image: "/assets/HongdaePocha/HongdaePocha_image/tteokbokki.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 59,
    name: "무조림 Mujorim",
    category: "Side Menu",
    subcategory: "Small Plates",
    image: "/assets/HongdaePocha/HongdaePocha_image/mujorim.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 60,
    name: "컵라면 볶음밥 Cup-ramyeon fried rice",
    category: "Side Menu",
    subcategory: "Small Plates",
    image: "/assets/HongdaePocha/HongdaePocha_image/cupramyenrice.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 61,
    name: "고추장 육회와 해시브라운 Gochujang yukhoe and hashbrowns",
    category: "Side Menu",
    subcategory: "Small Plates",
    image: "/assets/HongdaePocha/HongdaePocha_image/heshbrown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 62,
    name: "김치우동 Kimchi udong",
    category: "Side Menu",
    subcategory: "Small Plates",
    image: "/assets/HongdaePocha/HongdaePocha_image/kimchiodong.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 63,
    name: "바나나우유 아이스크림 (Banana Oo-yoo Ice Cream)",
    category: "Dessert",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 64,
    name: "녹차 아이스크림 (Nokcha Ice Cream)",
    category: "Dessert",
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 65,
    name: "공기밥 Steamed rice",
    category: "Extras",
    subcategory: null,
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 66,
    name: "우동 Udon",
    category: "Extras",
    subcategory: null,
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 67,
    name: "라면 Ramyeon",
    category: "Extras",
    subcategory: null,
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
  {
    id: 68,
    name: "치즈 Cheese",
    category: "Extras",
    subcategory: null,
    image: "/assets/HongdaePocha/HongdaePocha_image/unknown.jpg",
    isNew: false,
    isHot: false,
    isIce: false,
  },
];
